# Generated by Django 6.0.3 on 2026-05-06 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='servido',
            field=models.BooleanField(default=False),
        ),
    ]
